services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis # Service name of Redis
      - REDIS_PORT=6379 # Internal Redis port
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6380:6379" # Host port 6380 mapped to Redis internal port 6379
    
